# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Movie.create!(title: "Captain Marvel", genre: :action, link: "tkSuLa3o_5A")
Movie.create!(title: "Kung Fury", genre: :action, link: "bS5P_LAqiVg")
Movie.create!(title: "Operation Overlord", genre: :horror, link: "kQBCQpl4VMI")
Movie.create!(title: "Zabójcze maszyny", genre: :action, link: "5utVQRSIAYs")
Movie.create!(title: "The Lion King", genre: :animation, link: "4CbLXeGSDxg")
Movie.create!(title: "Aquaman", genre: :action, link: "h-k0-Z9b4Cw")
Movie.create!(title: "X-MEN Dark Phoenix", genre: :action, link: "QvpYp11Q7fA")
Movie.create!(title: "Bumblebee", genre: :action, link: "lcwmDAYt22k")
Movie.create!(title: "Robin Hood", genre: :action, link: "NXfjRgc8Dls")
Movie.create!(title: "Hotel Mumbai", genre: :drama, link: "ucYIwvZYGp8")
Movie.create!(title: "Arctic", genre: :drama, link: "rvtll41-dAc")
Movie.create!(title: "The Secret Life of Pets 2", genre: :animation, link: "0OkX3NomGQc")
Movie.create!(title: "The Prodigy", genre: :horror, link: "bVYjpOkH5ps")
Movie.create!(title: "Teen Spirit", genre: :drama, link: "z_Sqi-ashvU")
Movie.create!(title: "Men in Black International", genre: :action, link: "cAGy0JY_ygw")
Movie.create!(title: "Hellboy", genre: :action, link: "WYz-EsjXrtQ")
Movie.create!(title: "Greta", genre: :thriller, link: "jwSr1KnGPTo")
Movie.create!(title: "The LEGO Movie 2: The Second Part", genre: :animation, link: "PRl3GuXle80")
Movie.create!(title: "The Mustang", genre: :drama, link: "6W0KFTj50zI")
Movie.create!(title: "Captive State", genre: :thriller, link: "vuzplFd3YVY")
Movie.create!(title: "King of Thieves", genre: :drama, link: "1ywA8TtwJ50")
Movie.create!(title: "Bird Box", genre: :horror, link: "iW3t_wUDG5U")
Movie.create!(title: "Godzilla: King of the Monsters", genre: :action, link: "B12REtkl2KY")
Movie.create!(title: "Triple Frontier", genre: :action, link: "YWbrTLsplyA")
Movie.create!(title: "Brightburn", genre: :horror, link: "EKGATzNnr8c")
Movie.create!(title: "Avengers: Endgame", genre: :action, link: "ee1172yeqyE")
Movie.create!(title: "Spider-Man: Into the Spider-Verse", genre: :animation, link: "_aHDqS8EMn0")
Movie.create!(title: "The Lion King", genre: :animation, link: "zCecE7OyVMU")
Movie.create!(title: "Serenity", genre: :thriller, link: "eqDHqOcXjRQ")
Movie.create!(title: "Dumbo", genre: :animation, link: "ocWpGdITSR4")
Movie.create!(title: "Wonder Park", genre: :animation, link: "3_bUymlkSuA")
Movie.create!(title: "Alita: Battle Angel", genre: :action, link: "iaM3y7uDL90")
Movie.create!(title: "Toy Story 4", genre: :animation, link: "nMVDQZ34joY")
Movie.create!(title: "Missing Link", genre: :animation, link: "-6jCNhebfg8")
Movie.create!(title: "Salvation Boulevard", genre: :comedy, link: "u8760h5RksE")
Movie.create!(title: "Dolphin Tale", genre: :drama, link: "AJ_1eS2Erhk")
Movie.create!(title: "The Tree of Life", genre: :drama, link: "UVUXDn6hCY4")
Movie.create!(title: "Alvin and the Chipmunks: Chip-wrecked", genre: :animation, link: "DOa9xjdvomk")
Movie.create!(title: "Moneyball", genre: :drama, link: "-4QPVo0UIzc")
Movie.create!(title: "Puss in Boots", genre: :animation, link: "55gmAtakjJ4")
Movie.create!(title: "Harry Potter and the Deathly Hallows - Part 2", genre: :action, link: "monOjieIgA4")
Movie.create!(title: "R", genre: :drama, link: "VJKki0eIbwc")
Movie.create!(title: "Griff the Invisible", genre: :comedy, link: "So9Tia2qR1o")
Movie.create!(title: "30 Minutes or Less", genre: :comedy, link: "nfOt-Go3ECA")
Movie.create!(title: "Horrible Bosses", genre: :comedy, link: "pooyGS3atjg")
Movie.create!(title: "Killer Elite", genre: :thriller, link: "8F1wrDsUqYc")
Movie.create!(title: "The Names of Love", genre: :drama, link: "3U5Q8guKRpg")
Movie.create!(title: "The Tree", genre: :drama, link: "jRFo5ILvJR4")
Movie.create!(title: "Bad Teacher", genre: :comedy, link: "sxF-adi0Vjk")
Movie.create!(title: "Fading of the Cries", genre: :action, link: "BMOMrGch2TA")
